### ISSUE TITLE
'PluginNotFound' error 

### ISSUE THREAD

**Issue by nsahoo** [Run2-CMS-BPH/BsToPhiMuMu#9]
While running interactively over an edm root file, I found the error 

----- Begin Fatal Exception 16-Mar-2018 10:46:52 CET-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Unable to find plugin 'BsToPhiMuMu' in category 'CMS EDM Framework Module'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

The reason might be because of a missing plugin. Please fix ASAP.

**Comment by nsahoo** [comment]
Fixed.

**Comment by ridhichawla** [comment]
Can you please explain the solution?

**Comment by ridhichawla** [comment]
I am facing the same problem. Can you please explain the solution?

**Comment by nsahoo** [comment]
Hi @ridhichawla 

BTW, are you running this code for which year ? 2016 or 2017 ?

Best, Niladri.

**Comment by nsahoo** [comment]
Hi @ridhichawla

Are you joining BsToPhiMuMu angular analysis ? Why do you need this code ? 

Best, Niladri.

**Comment by ridhichawla** [comment]
Hi @nsahoo 

I should have written 'similar' instead of same. Sorry for the confusion.

I am facing this error while running my code for Drell-Yan 2015 analysis. The error is:

----- Begin Fatal Exception 13-Mar-2019 05:32:22 CET-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Unable to find plugin 'SimpleElectronNtupler' in category 'CMS EDM Framework Module'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

Here 'SimpleElectronNtupler' is the name of my ntuplizer.

Assuming that the reason for such an error might not be analysis specific, I asked for the solution that solved the error in your case.

Thanks,
Ridhi

**Comment by nsahoo** [comment]
Hi @ridhichawla 

apologies, I was away for a family function for last 3-4 days. If you don't mind, could you please put your (EDAnalyzer) code in some public area so that I can do the x-check myself ? 

Best, Niladri.
